# Generated by Django 4.0.1 on 2024-11-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название свойства, например, 'Цвет', 'Размер'.", max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='key',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='value',
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Значение свойства, например, 'Красный', 'XL'.", max_length=100)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.propertykey')),
            ],
        ),
        migrations.AddField(
            model_name='productproperty',
            name='property_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='shop.propertyvalue'),
            preserve_default=False,
        ),
    ]
