# Generated by Django 4.0.1 on 2024-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_propertykey_remove_productproperty_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(related_name='products', to='shop.PropertyValue'),
        ),
        migrations.DeleteModel(
            name='ProductProperty',
        ),
    ]
