# Generated by Django 4.0.1 on 2024-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_properties_delete_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='property_key_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
