# Generated by Django 4.0.1 on 2024-11-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_property_key_product_property_key_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='property_key',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_key_2',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=255),
        ),
    ]
